# Generated by Django 3.0 on 2020-05-30 22:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('order_statuses', 'Sifarişlər üçün'), ('declaration_statuses', 'Bəyənnamələr üçün')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'status',
                'ordering': ['order'],
                'unique_together': {('codename', 'type', 'order')},
            },
        ),
    ]
