# Generated by Django 3.0 on 2020-05-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='display_name_az',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='display_name_ru',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
