# Generated by Django 3.0 on 2020-05-31 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200530_1954'),
        ('fulfillment', '0005_auto_20200531_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cargo_price_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='product_price_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='real_cargo_price_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='real_product_price_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Currency'),
            preserve_default=False,
        ),
    ]
