# Generated by Django 3.0 on 2020-05-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0007_auto_20200531_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_comment',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('card', 'Kart'), ('cash', 'Nağd'), ('balance', 'Balans')], max_length=10),
        ),
    ]
