# Generated by Django 3.0 on 2020-06-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0008_auto_20200601_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_url',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
