# Generated by Django 3.0 on 2020-06-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0010_statusevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='type',
            field=models.CharField(choices=[('order_statuses', 'Sifarişlər üçün'), ('package_statuses', 'Bağlamalar üçün')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(choices=[('order_payment', 'Sifariş ödənişi'), ('package_payment', 'Bağlama ödənişi'), ('order_remainder_payment', 'Sifariş qalığı ödənişi'), ('order_refund', 'Sifarişin geri ödənişi'), ('package_refund', 'Bağlamanın geri ödənişi'), ('balance_increase', 'Balans artırılması'), ('balance_decrease', 'Balansdan çıxarış')], max_length=30),
        ),
    ]
