# Generated by Django 3.0 on 2020-06-03 23:10

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mobileoperator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fulfillment', '0011_auto_20200604_0254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('product_quantity', models.PositiveIntegerField(default=1)),
                ('product_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('weight', models.DecimalField(decimal_places=3, default=0, max_digits=9)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('total_in_usd', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('delivery_cost_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Currency')),
                ('product_price_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Currency')),
                ('source_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Country')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='related_packages', related_query_name='related_package', to='fulfillment.Status')),
                ('total_price_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', related_query_name='package', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'package',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', related_query_name='order', to='fulfillment.Package'),
        ),
    ]
