# Generated by Django 3.0 on 2020-06-05 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mobileoperator'),
        ('fulfillment', '0012_auto_20200604_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title_az', models.CharField(max_length=50, null=True)),
                ('title_ru', models.CharField(max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('discounted_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('min_weight', models.DecimalField(decimal_places=4, default=0, max_digits=9)),
                ('max_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('is_per_kg', models.BooleanField(default=False)),
                ('is_liquid', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', related_query_name='tariff', to='core.Country')),
                ('price_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Currency')),
            ],
            options={
                'db_table': 'tariff',
            },
        ),
    ]
