# Generated by Django 3.0 on 2020-06-05 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0013_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_liquid',
            field=models.BooleanField(default=False),
        ),
    ]
