# Generated by Django 3.0 on 2020-06-05 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mobileoperator'),
        ('fulfillment', '0014_package_is_liquid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='total_in_usd',
            new_name='total_for_monthly_spendings',
        ),
        migrations.AddField(
            model_name='package',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='delivery_cost_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Currency'),
        ),
    ]
