# Generated by Django 3.0 on 2020-06-06 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mobileoperator'),
        ('fulfillment', '0015_auto_20200606_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='total_price_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Currency'),
        ),
    ]
