# Generated by Django 3.0 on 2020-06-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0016_auto_20200606_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='external_tracking_code',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
    ]
