# Generated by Django 3.0 on 2020-06-06 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0018_package_user_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='delivery_cost',
            new_name='delivery_price',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='delivery_cost_currency',
            new_name='delivery_price_currency',
        ),
    ]
