# Generated by Django 3.0 on 2020-06-06 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0019_auto_20200606_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusevent',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fulfillment.Package'),
        ),
    ]
