# Generated by Django 3.0 on 2020-06-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0021_productcategory_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='product_types',
            field=models.ManyToManyField(blank=True, related_name='packages', related_query_name='package', to='fulfillment.ProductType'),
        ),
    ]
