# Generated by Django 3.0 on 2020-06-09 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mobileoperator'),
        ('fulfillment', '0022_package_product_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', related_query_name='address', to='core.Country')),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='AddressField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=300)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', related_query_name='field', to='fulfillment.Address')),
            ],
            options={
                'db_table': 'address_field',
            },
        ),
    ]
