# Generated by Django 3.0 on 2020-06-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0023_address_addressfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressfield',
            name='append_client_code',
            field=models.BooleanField(default=False),
        ),
    ]
