# Generated by Django 3.0 on 2020-06-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0024_addressfield_append_client_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_color',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_size',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
