# Generated by Django 3.0 on 2020-06-11 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200610_1725'),
        ('fulfillment', '0027_auto_20200611_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='destination_country',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='source_city',
        ),
        migrations.AlterField(
            model_name='tariff',
            name='destination_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='destination_tariffs', related_query_name='destination_tariff', to='core.City'),
            preserve_default=False,
        ),
    ]
