# Generated by Django 3.0 on 2020-06-13 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200610_1725'),
        ('fulfillment', '0028_auto_20200611_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='source_country',
        ),
        migrations.AddField(
            model_name='tariff',
            name='source_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='source_tariffs', related_query_name='source_tariff', to='core.City'),
            preserve_default=False,
        ),
    ]
