# Generated by Django 3.0 on 2020-06-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0029_auto_20200613_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tracking_code',
            new_name='order_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='package',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_comment',
        ),
        migrations.AddField(
            model_name='order',
            name='product_description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
