# Generated by Django 3.0 on 2020-06-13 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0030_auto_20200613_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', related_query_name='order', to='fulfillment.ProductType'),
        ),
    ]
