# Generated by Django 3.0 on 2020-06-13 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0031_order_product_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='user_comment',
            new_name='user_note',
        ),
        migrations.RemoveField(
            model_name='package',
            name='delivery_price',
        ),
        migrations.RemoveField(
            model_name='package',
            name='delivery_price_currency',
        ),
        migrations.RemoveField(
            model_name='package',
            name='external_tracking_code',
        ),
        migrations.RemoveField(
            model_name='package',
            name='is_liquid',
        ),
        migrations.RemoveField(
            model_name='package',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='package',
            name='product_types',
        ),
        migrations.RemoveField(
            model_name='package',
            name='total_for_monthly_spendings',
        ),
        migrations.RemoveField(
            model_name='package',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='package',
            name='total_price_currency',
        ),
        migrations.RemoveField(
            model_name='package',
            name='weight',
        ),
        migrations.AddField(
            model_name='package',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', related_query_name='package', to='fulfillment.ProductType'),
        ),
    ]
