# Generated by Django 3.0 on 2020-06-14 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0035_auto_20200614_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='country',
        ),
    ]
