# Generated by Django 3.0 on 2020-06-15 17:29

from django.db import migrations, models
import fulfillment.models.package


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0036_remove_productcategory_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=fulfillment.models.package.get_package_attachment_path),
        ),
        migrations.AddField(
            model_name='package',
            name='product_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
