# Generated by Django 3.0 on 2020-06-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0037_auto_20200615_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='tracking_code',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True),
        ),
    ]
