# Generated by Django 3.0 on 2020-06-15 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0038_auto_20200615_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='arrival_date',
            field=models.DateField(default=datetime.datetime(2020, 6, 15, 18, 19, 27, 16140, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
