# Generated by Django 3.0 on 2020-06-15 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0039_package_arrival_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusevent',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_events', related_query_name='status_event', to='fulfillment.Order'),
        ),
        migrations.AlterField(
            model_name='statusevent',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_events', related_query_name='status_event', to='fulfillment.Package'),
        ),
    ]
