# Generated by Django 3.0 on 2020-06-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0040_auto_20200615_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='status_last_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
