# Generated by Django 3.0 on 2020-06-15 19:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0041_package_status_last_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status_last_update_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 15, 19, 48, 59, 503784, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
