# Generated by Django 3.0 on 2020-06-15 20:13

from django.db import migrations


def set_empty_tracking_codes(apps, schema_editor):
    try:
        Package = apps.get_model("fulfillment", "Package")
    except LookupError:
        return

    i = 1
    for package in Package.objects.all():
        if not package.tracking_code:
            i += 1
            package.tracking_code = "RANDOMTRACKCODE%d" % i
            package.save()


class Migration(migrations.Migration):

    dependencies = [
        ("fulfillment", "0043_order_status_last_update_time"),
    ]

    operations = [
        migrations.RunPython(
            set_empty_tracking_codes, reverse_code=migrations.RunPython.noop
        )
    ]
