# Generated by Django 3.0 on 2020-06-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0044_auto_20200616_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='tracking_code',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
    ]
