# Generated by Django 3.0 on 2020-06-16 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200610_1725'),
        ('fulfillment', '0045_auto_20200616_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='package',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='package',
            name='product_price_currency',
        ),
        migrations.RemoveField(
            model_name='package',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='package',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='package',
            name='product_url',
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.CharField(default='TEST', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='external_order_code',
            field=models.CharField(db_index=True, default='TEST', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='is_volume_considered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='needs_description',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='product_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', related_query_name='orders', to='fulfillment.ProductCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='tracking_code',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', related_query_name='product', to='fulfillment.ProductCategory')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', related_query_name='product', to='fulfillment.Package')),
                ('price_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Currency')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', related_query_name='products', to='fulfillment.ProductType')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
