# Generated by Django 3.0 on 2020-06-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0048_auto_20200618_1721'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='status',
            unique_together={('codename', 'type')},
        ),
    ]
