# Generated by Django 3.0 on 2020-06-18 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0049_auto_20200618_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(limit_choices_to={'type': 'order_statuses'}, on_delete=django.db.models.deletion.PROTECT, related_name='related_orders', related_query_name='related_order', to='fulfillment.Status'),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.ForeignKey(limit_choices_to={'type': 'package_statuses'}, on_delete=django.db.models.deletion.PROTECT, related_name='related_packages', related_query_name='related_package', to='fulfillment.Status'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.ForeignKey(limit_choices_to={'type': 'shipment_statuses'}, on_delete=django.db.models.deletion.PROTECT, related_name='related_shipments', related_query_name='related_shipment', to='fulfillment.Status'),
        ),
    ]
