# Generated by Django 3.0 on 2020-06-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0050_auto_20200618_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
