# Generated by Django 3.0 on 2020-06-18 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0051_auto_20200618_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='number',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='foreign_shipments', related_query_name='foreign_shipment', to='fulfillment.Warehouse'),
        ),
    ]
