# Generated by Django 3.0 on 2020-06-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0053_auto_20200618_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
