# Generated by Django 3.0 on 2020-06-20 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_address_nearby_warehouse'),
        ('fulfillment', '0054_shipment_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='destination_user_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Address'),
        ),
    ]
