# Generated by Django 3.0 on 2020-06-20 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0055_shipment_destination_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Kart'), ('cash', 'Nağd'), ('balance', 'Balans')], default='balance', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statusevent',
            name='shipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_events', related_query_name='status_event', to='fulfillment.Shipment'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='invoice_number',
            field=models.CharField(db_index=True, default='TEST', max_length=35, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='ref_object_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(choices=[('order_payment', 'Sifariş ödənişi'), ('shipment_payment', 'Göndərmə ödənişi'), ('order_remainder_payment', 'Sifariş qalığı ödənişi'), ('order_refund', 'Sifarişin geri ödənişi'), ('shipment_refund', 'Göndərmənın geri ödənişi'), ('balance_increase', 'Balans artırılması'), ('balance_decrease', 'Balansdan çıxarış')], max_length=30),
        ),
    ]
