# Generated by Django 3.0 on 2020-06-20 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0056_auto_20200620_1514'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('purpose', 'ref_object_id')},
        ),
    ]
