# Generated by Django 3.0 on 2020-06-20 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fulfillment', '0057_auto_20200620_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='object_id',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='object_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='ref_object_id',
        ),
    ]
