# Generated by Django 3.0 on 2020-06-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0058_auto_20200620_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_oneclick',
            field=models.BooleanField(default=False),
        ),
    ]
