# Generated by Django 3.0 on 2020-06-21 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0059_shipment_is_oneclick'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fulfillment.Order'),
        ),
    ]
