# Generated by Django 3.0 on 2020-06-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0060_package_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='tracking_code',
        ),
        migrations.AddField(
            model_name='package',
            name='admin_tracking_code',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='user_tracking_code',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True),
        ),
    ]
