# Generated by Django 3.0 on 2020-06-23 13:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0063_comment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='invoice_number',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
