# Generated by Django 3.0 on 2020-06-23 18:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0065_auto_20200623_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='status_last_update_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
