# Generated by Django 3.0 on 2020-06-26 17:00

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200610_1725'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fulfillment', '0066_shipment_status_last_update_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'assignment',
            },
        ),
        migrations.CreateModel(
            name='ShoppingAssistantProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('assigned_orders', models.ManyToManyField(through='fulfillment.Assignment', to='fulfillment.Order')),
                ('countries', models.ManyToManyField(related_name='assitant_profiles', related_query_name='assistant_profile', to='core.Country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shopping_assistant',
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='assistant_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', related_query_name='assignment', to='fulfillment.ShoppingAssistantProfile'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_assignments', related_query_name='as_assignment', to='fulfillment.Order'),
        ),
    ]
