# Generated by Django 3.0 on 2020-06-26 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fulfillment', '0067_auto_20200626_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingassistantprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_staff': True, 'role__type': 'shopping_assistant'}, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
