# Generated by Django 3.0 on 2020-06-26 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0068_auto_20200626_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', related_query_name='child', to='fulfillment.Transaction'),
        ),
    ]
