# Generated by Django 3.0 on 2020-06-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0069_transaction_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='related_object_identifier',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(choices=[('order_payment', 'Sifariş ödənişi'), ('shipment_payment', 'Göndərmə ödənişi'), ('order_remainder_payment', 'Sifariş qalığı ödənişi'), ('order_refund', 'Sifarişin geri ödənişi'), ('shipment_refund', 'Göndərmənın geri ödənişi'), ('balance_increase', 'Balans artırılması'), ('balance_decrease', 'Balansdan çıxarış'), ('merged', 'Birləşmiş')], max_length=30),
        ),
    ]
