# Generated by Django 3.0 on 2020-06-27 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0070_auto_20200626_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='as_assignment', to='fulfillment.Order'),
        ),
    ]
