# Generated by Django 3.0 on 2020-06-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0075_auto_20200628_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='max_weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='min_weight',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(choices=[('order_payment', 'Sifariş ödənişi'), ('shipment_payment', 'Göndərmə ödənişi'), ('order_remainder_payment', 'Sifariş qalığı ödənişi'), ('order_refund', 'Sifarişin geri ödənişi'), ('order_remainder_refund', 'Sifarişin artıq ödənişin qaytarılması'), ('shipment_refund', 'Göndərmənın geri ödənişi'), ('balance_increase', 'Balans artırılması'), ('balance_decrease', 'Balansdan çıxarış'), ('merged', 'Birləşmiş')], max_length=30),
        ),
    ]
