# Generated by Django 3.0 on 2020-06-29 17:12

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fulfillment', '0076_auto_20200629_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingassistantprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='WarehousemanProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='warehouseman_profile', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehousemen', related_query_name='warehousemen', to='fulfillment.Warehouse')),
            ],
            options={
                'db_table': 'warehouseman_profile',
            },
        ),
    ]
