# Generated by Django 3.0 on 2020-06-29 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0078_auto_20200629_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='current_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', related_query_name='package', to='fulfillment.Warehouse'),
        ),
    ]
