# Generated by Django 3.0 on 2020-06-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0079_package_current_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
