# Generated by Django 3.0 on 2020-06-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0080_package_is_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='shelf',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
