# Generated by Django 3.0 on 2020-06-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0083_shipment_fixed_total_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='fixed_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='fixed_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='fixed_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_volume_considered',
            field=models.BooleanField(default=False),
        ),
    ]
