# Generated by Django 3.0 on 2020-06-29 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0085_auto_20200630_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='source_warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='boxes', related_query_name='box', to='fulfillment.Warehouse'),
            preserve_default=False,
        ),
    ]
