# Generated by Django 3.0 on 2020-06-29 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0086_box_source_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', related_query_name='shipment', to='fulfillment.Box'),
        ),
    ]
