# Generated by Django 3.0 on 2020-06-29 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0087_auto_20200630_0057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='box',
            unique_together={('code', 'source_warehouse')},
        ),
    ]
