# Generated by Django 3.0 on 2020-06-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0088_auto_20200630_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_by_assistant',
            field=models.BooleanField(default=False),
        ),
    ]
