# Generated by Django 3.0 on 2020-07-01 14:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0089_package_is_by_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='box',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('plane', 'Təyyarə')], default='plane', max_length=10)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accepted_flights', related_query_name='accepted_flight', to='fulfillment.Warehouse')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departure_flights', related_query_name='departure_flight', to='fulfillment.Warehouse')),
            ],
            options={
                'db_table': 'flight',
            },
        ),
        migrations.AddField(
            model_name='box',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boxes', related_query_name='box', to='fulfillment.Transport'),
        ),
    ]
