# Generated by Django 3.0 on 2020-07-02 18:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0091_auto_20200701_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='real_arrival_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
