# Generated by Django 3.0 on 2020-07-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0092_package_real_arrival_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='confirmed_properties',
            field=models.BooleanField(default=False),
        ),
    ]
