# Generated by Django 3.0 on 2020-07-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0093_shipment_confirmed_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='real_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
