# Generated by Django 3.0 on 2020-07-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0096_auto_20200703_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='flight',
            new_name='transportation',
        ),
        migrations.AddField(
            model_name='transportation',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
