# Generated by Django 3.0 on 2020-07-03 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fulfillment', '0099_shipment_current_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousemanprofile',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehousemen', related_query_name='warehouseman', to='fulfillment.Warehouse'),
        ),
        migrations.CreateModel(
            name='CashierProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='cashier_profile', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashiers', related_query_name='cashier', to='fulfillment.Warehouse')),
            ],
            options={
                'db_table': 'cashier_profile',
            },
        ),
    ]
