# Generated by Django 3.0 on 2020-07-04 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0100_auto_20200704_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='transportation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes', related_query_name='box', to='fulfillment.Transportation'),
        ),
    ]
