# Generated by Django 3.0 on 2020-07-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0103_auto_20200705_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='total_weight',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=9),
        ),
    ]
