# Generated by Django 3.0 on 2020-07-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0105_auto_20200705_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True),
        ),
    ]
