# Generated by Django 3.0 on 2020-07-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0107_auto_20200708_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='payment_method',
        ),
    ]
