# Generated by Django 3.0 on 2020-07-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0109_auto_20200708_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='title_az',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='title_ru',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
