# Generated by Django 3.0 on 2020-07-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0110_auto_20200708_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalservice',
            name='type',
            field=models.CharField(choices=[('for_packages', 'Bağlamalar üçün'), ('for_shipments', 'Göndərmələr üçün')], max_length=15),
        ),
    ]
