# Generated by Django 3.0 on 2020-07-08 16:11

from django.db import migrations, models
import django.db.models.deletion
import fulfillment.models.service


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0111_auto_20200708_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packageadditionalservice',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='packageadditionalservice',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_services', related_query_name='ordered_service', to='fulfillment.Package'),
        ),
        migrations.AlterField(
            model_name='shipmentadditionalservice',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_services', related_query_name='ordered_service', to='fulfillment.Shipment'),
        ),
        migrations.CreateModel(
            name='ShipmentAdditionalServiceAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=fulfillment.models.service.get_shipment_service_attachment_path)),
                ('ordered_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='fulfillment.ShipmentAdditionalService')),
            ],
            options={
                'db_table': 'shipment_service_attachment',
            },
        ),
        migrations.CreateModel(
            name='PackageAdditionalServiceAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=fulfillment.models.service.get_shipment_service_attachment_path)),
                ('ordered_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='fulfillment.PackageAdditionalService')),
            ],
            options={
                'db_table': 'package_service_attachment',
            },
        ),
    ]
