# Generated by Django 3.0 on 2020-07-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0112_auto_20200708_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentadditionalservice',
            name='attachment',
        ),
        migrations.AddField(
            model_name='packageadditionalservice',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentadditionalservice',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
