# Generated by Django 3.0 on 2020-07-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0113_auto_20200708_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='needs_note',
            field=models.BooleanField(default=False),
        ),
    ]
