# Generated by Django 3.0 on 2020-07-10 19:32

from django.db import migrations, models
import django.db.models.deletion
import fulfillment.models.service


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0114_additionalservice_needs_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='destination_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrived_transports', related_query_name='arrived_transport', to='core.City'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='source_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departured_transports', related_query_name='departured_transport', to='core.City'),
        ),
        migrations.AlterField(
            model_name='packageadditionalserviceattachment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=fulfillment.models.service.get_package_service_attachment_path),
        ),
    ]
