# Generated by Django 3.0 on 2020-07-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0116_auto_20200711_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='is_services',
            new_name='is_serviced',
        ),
    ]
