# Generated by Django 3.0 on 2020-07-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0117_auto_20200711_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='is_services',
            new_name='is_serviced',
        ),
    ]
