# Generated by Django 3.0 on 2020-07-11 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0118_auto_20200711_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='destination_warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='arrived_boxes', related_query_name='arrived_box', to='fulfillment.Warehouse'),
            preserve_default=False,
        ),
    ]
