# Generated by Django 3.0 on 2020-07-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0120_warehouse_codename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
