# Generated by Django 3.0 on 2020-07-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0121_auto_20200711_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportation',
            name='destination_warehouse',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='source_warehouse',
        ),
    ]
