# Generated by Django 3.0 on 2020-07-12 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_city_code'),
        ('fulfillment', '0122_auto_20200711_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', related_query_name='warehouse', to='core.Country'),
        ),
        migrations.CreateModel(
            name='WarehouseAdditionalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serving_warehouses', related_query_name='serving_warehouse', to='fulfillment.AdditionalService')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_services', related_query_name='allowed_service', to='fulfillment.Warehouse')),
            ],
            options={
                'db_table': 'warehouse_servoce',
            },
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='warehouses',
            field=models.ManyToManyField(related_name='services', related_query_name='service', through='fulfillment.WarehouseAdditionalService', to='fulfillment.Warehouse'),
        ),
    ]
