# Generated by Django 3.0 on 2020-07-15 16:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fulfillment', '0125_auto_20200713_0057'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cashierprofile',
            unique_together={('user', 'warehouse')},
        ),
    ]
