# Generated by Django 3.0 on 2020-07-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0127_monitor_queue_queueditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='last_queue_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
