# Generated by Django 3.0 on 2020-07-17 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0129_shipment_queued_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueditem',
            name='linked_warehouseman_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_cashier_item', to='fulfillment.QueuedItem'),
        ),
    ]
