# Generated by Django 3.0 on 2020-07-18 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0131_auto_20200718_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='queue',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fulfillment.Queue'),
        ),
    ]
