# Generated by Django 3.0 on 2020-07-19 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0132_auto_20200718_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queues', related_query_name='queue', to='fulfillment.Monitor'),
        ),
        migrations.AlterField(
            model_name='queueditem',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='monitor',
            unique_together={('code', 'warehouse')},
        ),
        migrations.AlterUniqueTogether(
            name='queueditem',
            unique_together={('queue', 'code')},
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='queue',
        ),
    ]
