# Generated by Django 3.0 on 2020-07-22 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_auto_20200722_1712'),
        ('fulfillment', '0134_auto_20200722_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='type',
            field=models.CharField(choices=[('cashier', 'Kassir növbəsi'), ('whman', 'Anbardar növbəsi'), ('cservice', 'Müştəri xidməti növbəsi')], max_length=10),
        ),
        migrations.AlterField(
            model_name='queueditem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queued_items', related_query_name='queued_item', to='customer.Customer'),
        ),
    ]
