# Generated by Django 3.0 on 2020-07-24 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fulfillment', '0135_auto_20200722_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queueditem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queued_items', related_query_name='queued_item', to=settings.AUTH_USER_MODEL),
        ),
    ]
