# Generated by Django 3.0 on 2020-07-24 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fulfillment', '0136_auto_20200724_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='object_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ['shipment', 'order']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
