# Generated by Django 3.0 on 2020-07-24 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0137_auto_20200725_0112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name_plural': 'Boxes'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Product categories'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['order'], 'verbose_name_plural': 'Statuses'},
        ),
    ]
