# Generated by Django 3.0 on 2020-07-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0138_auto_20200725_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_problematic',
            field=models.BooleanField(default=False),
        ),
    ]
