# Generated by Django 3.0 on 2020-07-26 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0139_package_is_problematic'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueditem',
            name='cashier_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queueditem',
            name='customer_service_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queueditem',
            name='for_cashier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queueditem',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queued_items', related_query_name='queued_item', to='fulfillment.Warehouse'),
        ),
        migrations.AddField(
            model_name='queueditem',
            name='warehouseman_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='queueditem',
            name='queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_items', related_query_name='queued_item', to='fulfillment.Queue'),
        ),
        migrations.AlterUniqueTogether(
            name='queueditem',
            unique_together={('warehouse', 'code')},
        ),
        migrations.RemoveField(
            model_name='queueditem',
            name='linked_warehouseman_item',
        ),
        migrations.RemoveField(
            model_name='queueditem',
            name='ready',
        ),
    ]
