# Generated by Django 3.0 on 2020-07-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0140_auto_20200726_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='last_queue_number',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='last_queue_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
