# Generated by Django 3.0 on 2020-07-26 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0141_auto_20200726_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueditem',
            name='dest_queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fulfillment.Queue'),
        ),
    ]
