# Generated by Django 3.0 on 2020-07-28 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0024_auto_20200728_2258'),
        ('core', '0013_configuration_is_active'),
        ('fulfillment', '0142_queueditem_dest_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='type',
            field=models.CharField(choices=[('order_statuses', 'Sifarişlər üçün'), ('package_statuses', 'Bağlamalar üçün'), ('shipment_statuses', 'Göndərmələr üçün'), ('courier_order_statuses', 'Kuryer sifarişləri üçün')], max_length=30),
        ),
        migrations.CreateModel(
            name='CourierTariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('region_az', models.CharField(max_length=255, null=True)),
                ('region_ru', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('discounted_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_tariffs', related_query_name='courier_tariff', to='core.City')),
                ('price_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Currency')),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='CourierProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='couriers', related_query_name='courier', to='core.City')),
                ('user', models.OneToOneField(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courier_profile',
            },
        ),
        migrations.CreateModel(
            name='CourierOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', related_query_name='order', to='fulfillment.CourierProfile')),
                ('destination_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customer.Address')),
                ('status', models.ForeignKey(limit_choices_to={'type': 'courier_order_statuses'}, on_delete=django.db.models.deletion.PROTECT, related_name='courier_orders', related_query_name='courier_order', to='fulfillment.Status')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fulfillment.CourierTariff')),
                ('total_price_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Currency')),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='courier_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', related_query_name='shipment', to='fulfillment.CourierTariff'),
        ),
    ]
