# Generated by Django 3.0 on 2020-07-31 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('fulfillment', '0143_auto_20200728_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('for_payment', 'Ödəniş üçün'), ('for_order', 'Sifariş üçün'), ('for_shipment', 'Göndərmə üçün'), ('for_package', 'Bağlama üçün'), ('other', 'Başqa')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('related_object_identifier', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('object_type', models.ForeignKey(blank=True, limit_choices_to={'model__in': ['shipment', 'order', 'transaction', 'package']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', related_query_name='notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
