# Generated by Django 3.0 on 2020-07-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0145_notification_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='body_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_az',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
