# Generated by Django 3.0 on 2020-07-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0147_notification_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='seen_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
