# Generated by Django 3.0 on 2020-08-01 12:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0148_notification_seen_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_service',
            field=models.CharField(blank=True, choices=[('cybersource', 'Cybersource')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_service_response_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_service_responsed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
