# Generated by Django 3.0 on 2020-08-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0153_auto_20200804_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='addressfield',
            options={'ordering': ['display_order']},
        ),
        migrations.RemoveField(
            model_name='address',
            name='display_order',
        ),
        migrations.AddField(
            model_name='addressfield',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
