# Generated by Django 3.0 on 2020-08-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0155_auto_20200804_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueditem',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
