# Generated by Django 3.0 on 2020-08-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0156_queueditem_is_checked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queueditem',
            name='is_checked',
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_checked_by_warehouseman',
            field=models.BooleanField(default=False),
        ),
    ]
