# Generated by Django 3.0 on 2020-08-07 14:12

from django.db import migrations, models
import django.db.models.deletion
import fulfillment.models.shipment


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0158_warehouse_is_universal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentReceiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_pin', models.CharField(max_length=7)),
                ('phone_number', models.CharField(max_length=20)),
                ('signature', models.ImageField(upload_to=fulfillment.models.shipment.get_shipment_receiver_signature_path)),
                ('is_real_owner', models.BooleanField(default=True)),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='fulfillment.Shipment')),
            ],
            options={
                'db_table': 'shipment_receiver',
            },
        ),
    ]
