# Generated by Django 3.0 on 2020-08-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0160_remove_notification_email_sent_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_sent_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
