# Generated by Django 3.0 on 2020-08-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0161_notification_email_sent_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentreceiver',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentreceiver',
            name='id_pin',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentreceiver',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentreceiver',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
