# Generated by Django 3.0 on 2020-08-15 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0162_auto_20200815_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arrived_boxes', related_query_name='arrived_box', to='fulfillment.Warehouse'),
        ),
    ]
