# Generated by Django 3.0 on 2020-08-18 08:45

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fulfillment", "0163_auto_20200815_2100"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationEvent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("package_problematic", "Problemli bağlama yarandı"),
                            ("package_foreign", "Bağlama xarici anbara daxil oldu"),
                            (
                                "shipment_tobeshipped",
                                "Göndərmə göndərilmək üçün hazır oldu",
                            ),
                            (
                                "shipment_ontheway",
                                "Göndərmə hava limanına təhvil verildi",
                            ),
                            ("shipment_received", "Gömdərmə yerli anbara daxil oldu"),
                            ("shipment_done", "Göndərmə müştəriyə təhvil verildi"),
                            (
                                "payment_shipment_create",
                                "Göndərmənin qiyməti təyin olundu və ödəniş yarandı",
                            ),
                            ("order_fulfill", "Sifariş köməkçi tərəfindən verildi"),
                            ("paymnet_order_create", "Sifariş üçün ödəniş yarandı"),
                            ("order_reject", "Sifariş köməkçi tərəfindən ləğv olundu"),
                            (
                                "order_remainder_refund",
                                "Sifarişin artıq ödənişi iadə edildi",
                            ),
                            (
                                "order_remainder_create",
                                "Sifarişin qalıq ödənişi yarandı",
                            ),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("title_az", models.CharField(max_length=255, null=True)),
                ("title_ru", models.CharField(max_length=255, null=True)),
                (
                    "web_text",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                (
                    "web_text_az",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                (
                    "web_text_ru",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                ("email_text_simple", models.TextField(blank=True, null=True)),
                ("email_text_simple_az", models.TextField(blank=True, null=True)),
                ("email_text_simple_ru", models.TextField(blank=True, null=True)),
                (
                    "email_text",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                (
                    "email_text_az",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                (
                    "email_text_ru",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                ("sms_text", models.TextField(blank=True, null=True)),
                ("sms_text_az", models.TextField(blank=True, null=True)),
                ("sms_text_ru", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "notification_event",
                "unique_together": {("reason", "is_active")},
            },
        ),
    ]
