# Generated by Django 3.0 on 2020-08-19 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0164_trackingstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackingstatus',
            options={'verbose_name_plural': 'Tracking statuses'},
        ),
    ]
