# Generated by Django 3.0 on 2020-08-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0165_auto_20200819_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingstatus',
            name='tracking_code',
            field=models.CharField(max_length=4),
        ),
    ]
