# Generated by Django 3.0 on 2020-08-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0166_auto_20200819_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingstatus',
            name='tracking_condition_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
