# Generated by Django 3.0 on 2020-08-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0168_auto_20200819_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingstatus',
            name='pl_number',
            field=models.CharField(max_length=5),
        ),
    ]
