# Generated by Django 3.0 on 2020-08-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0171_trackingstatus_customs_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_service',
            field=models.CharField(blank=True, choices=[('cybersource', 'Cybersource'), ('paypal', 'PayPal')], max_length=30, null=True),
        ),
    ]
