# Generated by Django 3.0 on 2020-08-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0172_auto_20200821_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalservice',
            name='description_en_US',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='additionalservice',
            name='title_en_US',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='body_en_US',
            field=models.TextField(default=str, null=True),
        ),
        migrations.AddField(
            model_name='couriertariff',
            name='region_en_US',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='body_en_US',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_en_US',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_en_US',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producttype',
            name='name_en_US',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='display_name_en_US',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='statusevent',
            name='message_en_US',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tariff',
            name='title_en_US',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trackingstatus',
            name='mandatory_comment_en_US',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingstatus',
            name='problem_code_description_en_US',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingstatus',
            name='tracking_code_description_en_US',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingstatus',
            name='tracking_code_explanation_en_US',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackingstatus',
            name='tracking_condition_code_description_en_US',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='type',
            field=models.CharField(choices=[('order_statuses', 'Sifarişlər üçün'), ('package_statuses', 'Sifarişlər üçün'), ('shipment_statuses', 'Sifarişlər üçün'), ('courier_order_statuses', 'Sifarişlər üçün')], max_length=30),
        ),
    ]
