# Generated by Django 3.0 on 2020-08-25 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0176_contactusmessage_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalservice',
            old_name='description_en_US',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='additionalservice',
            old_name='title_en_US',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body_en_US',
            new_name='body_en',
        ),
        migrations.RenameField(
            model_name='couriertariff',
            old_name='region_en_US',
            new_name='region_en',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='body_en_US',
            new_name='body_en',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='title_en_US',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='name_en_US',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='producttype',
            old_name='name_en_US',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='display_name_en_US',
            new_name='display_name_en',
        ),
        migrations.RenameField(
            model_name='statusevent',
            old_name='message_en_US',
            new_name='message_en',
        ),
        migrations.RenameField(
            model_name='tariff',
            old_name='title_en_US',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='trackingstatus',
            old_name='mandatory_comment_en_US',
            new_name='mandatory_comment_en',
        ),
        migrations.RenameField(
            model_name='trackingstatus',
            old_name='problem_code_description_en_US',
            new_name='problem_code_description_en',
        ),
        migrations.RenameField(
            model_name='trackingstatus',
            old_name='tracking_code_description_en_US',
            new_name='tracking_code_description_en',
        ),
        migrations.RenameField(
            model_name='trackingstatus',
            old_name='tracking_code_explanation_en_US',
            new_name='tracking_code_explanation_en',
        ),
        migrations.RenameField(
            model_name='trackingstatus',
            old_name='tracking_condition_code_description_en_US',
            new_name='tracking_condition_code_description_en',
        ),
    ]
