# Generated by Django 3.0 on 2020-08-28 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fulfillment.models.ticket


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('fulfillment', '0178_auto_20200825_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=15, null=True)),
                ('related_object_identifier', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('problem_descrtipion', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_az', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('can_select_order', models.BooleanField(default=True)),
                ('can_select_package', models.BooleanField(default=True)),
                ('can_select_shipment', models.BooleanField(default=True)),
                ('can_select_payment', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ticket_category',
            },
        ),
        migrations.AlterField(
            model_name='status',
            name='type',
            field=models.CharField(choices=[('order_statuses', 'Sifarişlər üçün'), ('package_statuses', 'Bağlamalar üçün'), ('shipment_statuses', 'Göndərmələr üçün'), ('courier_order_statuses', 'Kuryer sifarişləri üçün'), ('ticket_statuses', 'Müraciətlər üçün')], max_length=30),
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', related_query_name='ticket_comment', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', related_query_name='comment', to='fulfillment.Ticket')),
            ],
            options={
                'db_table': 'ticket_comment',
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=fulfillment.models.ticket.get_ticket_attachment_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_attachments', related_query_name='comment_attachment', to='fulfillment.TicketComment')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_attachments', related_query_name='ticket_attachment', to='fulfillment.Ticket')),
            ],
            options={
                'db_table': 'ticket_attachment',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', related_query_name='ticket', to='fulfillment.TicketCategory'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='object_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ['shipment', 'order', 'transaction', 'package']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(limit_choices_to={'type': 'ticket_statuses'}, on_delete=django.db.models.deletion.PROTECT, related_name='related_tickets', related_query_name='related_ticket', to='fulfillment.Status'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', related_query_name='ticket', to=settings.AUTH_USER_MODEL),
        ),
    ]
