# Generated by Django 3.0 on 2020-08-28 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0179_auto_20200828_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'verbose_name_plural': 'Ticket categories'},
        ),
    ]
