# Generated by Django 3.0 on 2020-08-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0180_auto_20200828_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcategory',
            name='can_select_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='can_select_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='can_select_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='can_select_shipment',
            field=models.BooleanField(default=False),
        ),
    ]
