# Generated by Django 3.0 on 2020-08-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0181_auto_20200828_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='problem_descrtipion',
            new_name='problem_description',
        ),
    ]
