# Generated by Django 3.0 on 2020-08-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0182_auto_20200828_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Can be seen by user'),
        ),
    ]
