# Generated by Django 3.0 on 2020-08-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0183_status_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='is_public',
        ),
    ]
