# Generated by Django 3.0 on 2020-08-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0185_ticketcomment_is_by_customer_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status_last_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
