# Generated by Django 3.0 on 2020-08-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0185_ticketcomment_is_by_customer_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressfield',
            name='append_user_full_name',
            field=models.BooleanField(default=False),
        ),
    ]
