# Generated by Django 3.0 on 2020-08-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0186_ticket_status_last_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='answered_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
