# Generated by Django 3.0 on 2020-08-29 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0032_frozenrecipient'),
        ('fulfillment', '0187_auto_20200829_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', related_query_name='order', to='customer.FrozenRecipient'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', related_query_name='shipment', to='customer.FrozenRecipient'),
        ),
    ]
