# Generated by Django 3.0 on 2020-08-29 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0188_auto_20200829_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fulfillment.Warehouse'),
        ),
    ]
