# Generated by Django 3.0 on 2020-08-30 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0186_shipment_source_country'),
        ('fulfillment', '0164_notificationevent'),
        ('fulfillment', '0189_order_destination_warehouse'),
        ('fulfillment', '0187_ticket_answered_by_admin'),
    ]

    operations = [
    ]
