# Generated by Django 3.0 on 2020-08-30 12:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0190_merge_20200830_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationevent',
            name='email_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='email_text_simple_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='sms_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='web_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
