# Generated by Django 3.0 on 2020-08-30 20:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0191_auto_20200830_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fulfillment.NotificationEvent'),
        ),
        migrations.AddField(
            model_name='notification',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='web_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='web_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='web_text_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='web_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='web_text_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
