# Generated by Django 3.0 on 2020-08-31 10:53

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0192_auto_20200831_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='body',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='body_az',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='body_en',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='body_ru',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='notificationevent',
            name='title_az',
        ),
        migrations.RemoveField(
            model_name='notificationevent',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='notificationevent',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='notification',
            name='email_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_subject_az',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_subject_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_subject_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_text_az',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_text_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_text_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_text_simple',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_text_simple_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_text_simple_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_text_simple_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='must_be_seen_on_web',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_text_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='web_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='web_text_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='web_text_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='web_text_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='web_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='web_title_az',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='web_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='web_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='email_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='email_subject_az',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='email_subject_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='email_subject_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='web_title_az',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='web_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notificationevent',
            name='web_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
