# Generated by Django 3.0 on 2020-08-31 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0194_auto_20200831_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couriertariff',
            name='city',
        ),
        migrations.RemoveField(
            model_name='couriertariff',
            name='price_currency',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='courier_order',
        ),
        migrations.DeleteModel(
            name='CourierOrder',
        ),
        migrations.DeleteModel(
            name='CourierTariff',
        ),
    ]
