# Generated by Django 3.0 on 2020-08-31 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_country_flag_image'),
        ('customer', '0035_delete_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fulfillment', '0195_auto_20200831_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('discounted_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_areas', related_query_name='courier_area', to='core.City')),
                ('price_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Currency')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courier_areas', related_query_name='courier_area', to='fulfillment.Warehouse')),
            ],
            options={
                'db_table': 'courier_area',
            },
        ),
        migrations.CreateModel(
            name='CourierRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_regions', related_query_name='courier_region', to='fulfillment.CourierArea')),
            ],
            options={
                'db_table': 'courier_region',
            },
        ),
        migrations.CreateModel(
            name='CourierOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', related_query_name='order', to='fulfillment.CourierProfile')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier_orders', related_query_name='courier_order', to='customer.FrozenRecipient')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fulfillment.CourierRegion')),
                ('status', models.ForeignKey(limit_choices_to={'type': 'courier_order_statuses'}, on_delete=django.db.models.deletion.PROTECT, related_name='courier_orders', related_query_name='courier_order', to='fulfillment.Status')),
                ('total_price_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_orders', related_query_name='courier_order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courier_order',
            },
        ),
    ]
