# Generated by Django 3.0 on 2020-09-01 06:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0198_add_courier_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courierorder',
            name='failed_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courierorder',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courierorder',
            name='number',
            field=models.CharField(db_index=True, default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courierorder',
            name='status_last_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courierorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='courier_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', related_query_name='shipment', to='fulfillment.CourierOrder'),
        ),
    ]
