# Generated by Django 3.0 on 2020-09-01 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_country_flag_image'),
        ('fulfillment', '0200_auto_20200901_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(choices=[('order_payment', 'Sifariş ödənişi'), ('shipment_payment', 'Göndərmə ödənişi'), ('order_remainder_payment', 'Sifariş qalığı ödənişi'), ('courier_order_payment', 'Kuryer ödənişi'), ('order_refund', 'Sifarişin geri ödənişi'), ('order_remainder_refund', 'Sifarişin artıq ödənişin qaytarılması'), ('shipment_refund', 'Göndərmənın geri ödənişi'), ('balance_increase', 'Balans artırılması'), ('balance_decrease', 'Balansdan çıxarış'), ('merged', 'Birləşmiş')], max_length=30),
        ),
    ]
