# Generated by Django 3.0 on 2020-09-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0201_auto_20200901_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=9, null=True),
        ),
    ]
