# Generated by Django 3.0 on 2020-09-01 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_country_flag_image'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('fulfillment', '0202_auto_20200901_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='from_balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_balance_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='object_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ['shipment', 'order', 'courierorder']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
