# Generated by Django 3.0 on 2020-09-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0203_auto_20200901_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_partial',
            field=models.BooleanField(default=False),
        ),
    ]
