# Generated by Django 3.0 on 2020-09-02 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_country_flag_image'),
        ('fulfillment', '0204_transaction_is_partial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='real_commission_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='order',
            name='real_commission_price_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Currency'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='cargo_price_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Currency'),
        ),
    ]
