# Generated by Django 3.0 on 2020-09-02 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fulfillment', '0205_auto_20200902_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='object_type',
            field=models.ForeignKey(blank=True, limit_choices_to={'model__in': ['shipment', 'order', 'transaction', 'package', 'user']}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='notificationevent',
            name='reason',
            field=models.CharField(choices=[('user_email_preactivate', 'İstifadəçi profildə e-poçt yazanda'), ('package_problematic', 'Problemli bağlama yarandı'), ('package_foreign', 'Bağlama xarici anbara daxil oldu'), ('shipment_tobeshipped', 'Göndərmə göndərilmək üçün hazır oldu'), ('shipment_ontheway', 'Göndərmə hava limanına təhvil verildi'), ('shipment_received', 'Göndərmə yerli anbara daxil oldu'), ('shipment_done', 'Göndərmə müştəriyə təhvil verildi'), ('shipment_customs', 'Göndərmə gömrükdə yoxlanışdan keçdi'), ('payment_shipment_create', 'Göndərmənin qiyməti təyin olundu və ödəniş yarandı'), ('order_fulfill', 'Sifariş köməkçi tərəfindən verildi'), ('paymnet_order_create', 'Sifariş üçün ödəniş yarandı'), ('order_reject', 'Sifariş köməkçi tərəfindən ləğv olundu'), ('order_remainder_refund', 'Sifarişin artıq ödənişi iadə edildi'), ('order_remainder_create', 'Sifarişin qalıq ödənişi yarandı'), ('order_remainder_update', 'Sifarişin artıq ödənişi yeniləndi'), ('order_comment', 'Sifarişə köməkçi tərəfindən rəy yazıldı')], max_length=50),
        ),
    ]
