# Generated by Django 3.0 on 2020-09-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0206_auto_20200902_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
