# Generated by Django 3.0 on 2020-09-05 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0037_user_birth_date'),
        ('fulfillment', '0208_transaction_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueditem',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customer.FrozenRecipient'),
        ),
        migrations.AlterField(
            model_name='addressfield',
            name='value',
            field=models.CharField(blank=True, default=str, max_length=300),
        ),
    ]
