# Generated by Django 3.0 on 2020-09-05 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_country_display_order'),
        ('fulfillment', '0211_auto_20200905_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCountryLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(db_index=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_logs', related_query_name='country_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_country_log',
                'unique_together': {('user', 'country')},
            },
        ),
    ]
