# Generated by Django 3.0 on 2020-09-06 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200906_1356'),
        ('fulfillment', '0212_usercountrylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='total_price_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Currency'),
        ),
    ]
