# Generated by Django 3.1.1 on 2020-09-08 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0215_auto_20200909_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierorder',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fulfillment.couriertariff'),
        ),
    ]
