# Generated by Django 3.1.1 on 2020-09-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0216_courierorder_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='declared_items_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
