# Generated by Django 3.1.1 on 2020-09-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0217_shipment_declared_items_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='max_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='min_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
