# Generated by Django 3.1.1 on 2020-09-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0219_auto_20200910_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='is_fixed_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='is_dangerous',
            field=models.BooleanField(default=False, verbose_name='Is for liquid products'),
        ),
    ]
