# Generated by Django 3.1.1 on 2020-09-10 13:59

from django.db import migrations


def autoset_is_fixed_price_field_for_tariff(apps, schema_editor):
    Tariff = apps.get_model("fulfillment", "Tariff")
    Tariff.objects.filter(min_weight=0).update(is_fixed_price=True)


def reverse_autoset(apps, chema_editor):
    Tariff = apps.get_model("fulfillment", "Tariff")
    Tariff.objects.filter(min_weight=0).update(is_fixed_price=False)


class Migration(migrations.Migration):

    dependencies = [
        ("fulfillment", "0220_auto_20200910_1748"),
    ]

    operations = [
        migrations.RunPython(
            autoset_is_fixed_price_field_for_tariff, reverse_code=reverse_autoset
        )
    ]
