# Generated by Django 3.1.1 on 2020-09-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0221_tariff_fixed_price_field_auto_detect'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='manifest',
            field=models.FileField(blank=True, null=True, upload_to='manifests/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='transportation',
            name='packing_list',
            field=models.FileField(blank=True, null=True, upload_to='packing-lists/%Y/%m/%d/'),
        ),
    ]
