# Generated by Django 3.1.1 on 2020-09-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0222_auto_20200910_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='manifest_last_export_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='packing_list_last_export_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
