# Generated by Django 3.1.1 on 2020-09-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0224_notification_lang_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='seller',
            field=models.CharField(default='Noon.com', max_length=100),
            preserve_default=False,
        ),
    ]
