# Generated by Django 3.1.1 on 2020-09-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0226_auto_20200913_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='seller',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
