# Generated by Django 3.1.1 on 2020-09-14 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20200914_1327'),
        ('fulfillment', '0227_auto_20200914_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='airport_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.city'),
        ),
    ]
