# Generated by Django 3.1.1 on 2020-09-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0230_auto_20200916_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_seller',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='seller',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
