# Generated by Django 3.1.1 on 2020-09-19 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0231_auto_20200918_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', related_query_name='orders', to='fulfillment.productcategory'),
        ),
    ]
