# Generated by Django 3.1.1 on 2020-09-19 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0232_auto_20200919_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='transportation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boxes', related_query_name='box', to='fulfillment.transportation'),
        ),
    ]
