# Generated by Django 3.1.1 on 2020-09-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0233_auto_20200919_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_seller_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='seller_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
