# Generated by Django 3.1.1 on 2020-09-20 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0235_transportation_is_ar'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/previews/%Y/%d/%m'),
        ),
    ]
