# Generated by Django 3.1.1 on 2020-09-24 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20200922_2207'),
        ('fulfillment', '0238_auto_20200923_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='commission_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='product',
            name='commission_price_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency'),
        ),
    ]
