# Generated by Django 3.1.1 on 2020-10-03 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fulfillment', '0239_auto_20200924_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerServiceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_description', models.TextField(blank=True, null=True)),
                ('problem_description', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_service_requests', related_query_name='customer_service_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_service_log',
            },
        ),
    ]
