# Generated by Django 3.1.1 on 2020-10-03 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0240_customerservicelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerservicelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
