# Generated by Django 3.1.2 on 2020-10-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0241_customerservicelog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierorder',
            name='additional_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
