# Generated by Django 3.1.2 on 2020-10-10 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0242_order_product_image_url'),
        ('fulfillment', '0242_courierorder_additional_note'),
    ]

    operations = [
    ]
