# Generated by Django 3.1.2 on 2020-10-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0243_merge_20201010_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('logo', models.ImageField(upload_to='shop-logos/%Y/%m/%d')),
            ],
            options={
                'db_table': 'shop',
            },
        ),
    ]
