# Generated by Django 3.1.2 on 2020-10-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0245_order_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='show_on_slider',
            field=models.BooleanField(default=True),
        ),
    ]
