# Generated by Django 3.1.2 on 2020-10-14 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0041_auto_20200922_2207'),
        ('fulfillment', '0246_order_show_on_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_description', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=600)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.URLField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('shipping_price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.country')),
                ('price_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordered_products', related_query_name='ordered_product', to='fulfillment.productcategory')),
                ('shipping_price_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_products', related_query_name='ordered_product', to='fulfillment.shop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ordered_product',
            },
        ),
    ]
