# Generated by Django 3.1.2 on 2020-10-14 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0247_orderedproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedproduct',
            old_name='product_category',
            new_name='category',
        ),
    ]
