# Generated by Django 3.1.2 on 2020-10-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0248_auto_20201014_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
