# Generated by Django 3.1.2 on 2020-10-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0250_auto_20201014_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
