# Generated by Django 3.1.2 on 2020-10-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0251_auto_20201014_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
