# Generated by Django 3.1.2 on 2020-10-20 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0252_auto_20201015_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cashback_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashbacks', related_query_name='cashback', to='fulfillment.transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(choices=[('order_payment', 'Sifariş ödənişi'), ('shipment_payment', 'Göndərmə ödənişi'), ('order_remainder_payment', 'Sifariş qalığı ödənişi'), ('courier_order_payment', 'Kuryer ödənişi'), ('order_refund', 'Sifarişin geri ödənişi'), ('order_remainder_refund', 'Sifarişin artıq ödənişin qaytarılması'), ('shipment_refund', 'Göndərmənın geri ödənişi'), ('balance_increase', 'Balans artırılması'), ('balance_decrease', 'Balansdan çıxarış'), ('cashback', 'Cashback'), ('merged', 'Birləşmiş')], max_length=30),
        ),
    ]
