# Generated by Django 3.1.2 on 2020-10-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0255_product_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
