# Generated by Django 3.1.2 on 2020-10-21 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0254_shipment_extra'),
        ('fulfillment', '0256_assignment_deleted_at'),
    ]

    operations = [
    ]
