# Generated by Django 3.1.2 on 2020-10-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0257_auto_20201026_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='box',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='box',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='shipment',
            name='contains_batteries',
            field=models.BooleanField(default=False),
        ),
    ]
