# Generated by Django 3.1.2 on 2020-11-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0258_auto_20201027_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='url',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
