# Generated by Django 3.1.2 on 2020-11-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0260_auto_20201102_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='user_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
