# Generated by Django 3.1.2 on 2020-11-05 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fulfillment', '0260_auto_20201102_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('reason', models.CharField(choices=[('sd', 'Endirim'), ('ifd', 'Promo kod endirimi')], default='sd', max_length=3)),
                ('object_id', models.CharField(db_index=True, max_length=15)),
                ('object_type', models.ForeignKey(limit_choices_to={'model__in': ['shipment', 'order', 'courierorder']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'discount',
            },
        ),
    ]
