# Generated by Django 3.1.2 on 2020-11-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0262_auto_20201110_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
