# Generated by Django 3.1.2 on 2020-11-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0262_auto_20201105_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
