# Generated by Django 3.1.2 on 2020-11-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0262_auto_20201110_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='admin_tracking_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='user_tracking_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True),
        ),
    ]
