# Generated by Django 3.1.2 on 2020-11-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0263_auto_20201110_2317'),
        ('fulfillment', '0263_auto_20201111_1240'),
    ]

    operations = [
    ]
