# Generated by Django 3.1.2 on 2020-11-07 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('fulfillment', '0263_discount_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'promo_code',
            },
        ),
        migrations.CreateModel(
            name='PromoCodeBenefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(db_index=True, max_length=15)),
                ('related_object_identifier', models.CharField(db_index=True, max_length=50)),
                ('related_object_is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumed_benefits', related_query_name='consumed_benefit', to=settings.AUTH_USER_MODEL)),
                ('object_type', models.ForeignKey(limit_choices_to={'model__in': ['shipment', 'order', 'courierorder']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_benefits', related_query_name='used_benefit', to='fulfillment.promocode')),
            ],
            options={
                'db_table': 'promo_code_benefit',
            },
        ),
    ]
