# Generated by Django 3.1.2 on 2020-11-13 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0264_merge_20201111_1507'),
        ('fulfillment', '0257_merge_20201022_0358'),
    ]

    operations = [
    ]
