# Generated by Django 3.1.2 on 2020-11-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0264_promocode_promocodebenefit'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodebenefit',
            name='used_by_owner',
            field=models.BooleanField(default=False),
        ),
    ]
