# Generated by Django 3.1.2 on 2020-11-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0264_merge_20201111_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='ordering_starts_at',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
