# Generated by Django 3.1.2 on 2020-11-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0265_transportation_ordering_starts_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='ordering_starts_at',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
