# Generated by Django 3.1.2 on 2020-11-08 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0265_promocodebenefit_used_by_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocodebenefit',
            name='related_object_is_deleted',
        ),
    ]
