# Generated by Django 3.1.2 on 2020-11-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0266_remove_promocodebenefit_related_object_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodebenefit',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
