# Generated by Django 3.1.2 on 2020-11-14 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0265_merge_20201113_1647'),
        ('fulfillment', '0266_auto_20201113_1638'),
    ]

    operations = [
    ]
