# Generated by Django 3.1.2 on 2020-11-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0267_merge_20201114_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='completed_manually',
            field=models.BooleanField(default=False),
        ),
    ]
