# Generated by Django 3.1.2 on 2020-11-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0267_promocodebenefit_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodebenefit',
            name='used_by_consumer',
            field=models.BooleanField(default=False),
        ),
    ]
