# Generated by Django 3.1.2 on 2020-11-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fulfillment', '0268_promocodebenefit_used_by_consumer'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promocodebenefit',
            unique_together={('object_type', 'object_id')},
        ),
    ]
