# Generated by Django 3.1.2 on 2020-11-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0268_productphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='warehouseman_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
