# Generated by Django 3.1.2 on 2020-11-19 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0267_merge_20201114_1423'),
        ('fulfillment', '0269_auto_20201108_1915'),
    ]

    operations = [
    ]
