# Generated by Django 3.1.2 on 2020-11-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0268_transaction_completed_manually'),
        ('fulfillment', '0271_auto_20201124_0110'),
    ]

    operations = [
    ]
