# Generated by Django 3.1.2 on 2020-12-02 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0270_merge_20201119_2204'),
        ('fulfillment', '0272_merge_20201127_1537'),
    ]

    operations = [
    ]
