# Generated by Django 3.1.2 on 2020-12-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0268_auto_20201126_2121'),
        ('fulfillment', '0272_merge_20201127_1537'),
    ]

    operations = [
    ]
