# Generated by Django 3.1.2 on 2020-12-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0273_merge_20201202_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='user_tracking_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(condition=models.Q(deleted_at__isnull=True), fields=('user_tracking_code',), name='unique_tracking_code_when_not_deleted'),
        ),
    ]
