# Generated by Django 3.1.2 on 2020-12-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0273_merge_20201202_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='staff_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
