# Generated by Django 3.1.2 on 2020-12-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0273_merge_20201202_1704'),
        ('fulfillment', '0273_merge_20201202_2337'),
    ]

    operations = [
    ]
