# Generated by Django 3.1.2 on 2020-12-09 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0274_auto_20201208_1808'),
        ('fulfillment', '0274_shipment_staff_note'),
    ]

    operations = [
    ]
