# Generated by Django 3.1.2 on 2020-12-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0275_merge_20201209_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expenses',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
