# Generated by Django 3.1.2 on 2020-12-16 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0275_merge_20201209_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_az', models.CharField(max_length=200, null=True)),
                ('name_ru', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Parent Product Categories',
                'db_table': 'parent_product_category',
            },
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name_az',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', related_query_name='child', to='fulfillment.parentproductcategory'),
        ),
    ]
