# Generated by Django 3.1.2 on 2020-12-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0276_transaction_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expenses',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
