# Generated by Django 3.1.2 on 2020-12-16 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0276_auto_20201216_1940'),
        ('fulfillment', '0276_auto_20201216_2010'),
    ]

    operations = [
    ]
