# Generated by Django 3.1.2 on 2020-12-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0277_auto_20201211_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='expenses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courierorder',
            name='expenses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expenses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='expenses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='expenses',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='expenses',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
