# Generated by Django 3.1.2 on 2020-12-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0277_merge_20201217_0017'),
        ('fulfillment', '0278_auto_20201217_1949'),
    ]

    operations = [
    ]
