# Generated by Django 3.1.2 on 2020-12-18 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0279_merge_20201217_2011'),
        ('fulfillment', '0278_auto_20201217_1921'),
    ]

    operations = [
    ]
