# Generated by Django 3.1.2 on 2020-12-18 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0280_merge_20201218_1726'),
        ('fulfillment', '0274_merge_20201209_1602'),
    ]

    operations = [
    ]
