# Generated by Django 3.1.2 on 2020-12-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0281_merge_20201219_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierorder',
            name='extra',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
