# Generated by Django 3.1.2 on 2020-12-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0282_courierorder_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationevent',
            name='reason',
            field=models.CharField(choices=[('user_email_preactivate', 'İstifadəçi profildə e-poçt yazanda'), ('user_balance_topup', 'İstifadəçi balansı uğurla artırdı'), ('package_problematic', 'Problemli bağlama yarandı'), ('package_foreign', 'Bağlama xarici anbara daxil oldu'), ('shipment_tobeshipped', 'Göndərmə göndərilmək üçün hazır oldu'), ('shipment_ontheway', 'Göndərmə hava limanına təhvil verildi'), ('shipment_received', 'Göndərmə yerli anbara daxil oldu'), ('shipment_done', 'Göndərmə müştəriyə təhvil verildi'), ('shipment_customs', 'Göndərmə gömrükdə yoxlanışdan keçdi'), ('payment_shipment_create', 'Göndərmənin qiyməti təyin olundu və ödəniş yarandı'), ('order_fulfill', 'Sifariş köməkçi tərəfindən verildi'), ('paymnet_order_create', 'Sifariş üçün ödəniş yarandı'), ('order_reject', 'Sifariş köməkçi tərəfindən ləğv olundu'), ('order_remainder_refund', 'Sifarişin artıq ödənişi iadə edildi'), ('order_remainder_create', 'Sifarişin qalıq ödənişi yarandı'), ('order_remainder_update', 'Sifarişin artıq ödənişi yeniləndi'), ('order_comment', 'Sifarişə köməkçi tərəfindən rəy yazıldı'), ('order_external_code_add', 'Sifarişə köməkçi tərəfindən mağaza sifariş kodu əlavə edildi'), ('invite_friend_cashback_c', 'Promo kodu istifadə edib cashback qazandı'), ('invite_friend_cashback_o', 'Promo kodu dostuna verib cashback qazandı')], max_length=50),
        ),
    ]
