# Generated by Django 3.1.2 on 2020-12-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0283_auto_20201219_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='value',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
