# Generated by Django 3.1.2 on 2020-12-21 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_merge_20201209_1602'),
        ('fulfillment', '0285_auto_20201221_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodebenefit',
            name='cashback_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='promocodebenefit',
            name='cashback_amount_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.currency'),
        ),
    ]
