# Generated by Django 3.1.2 on 2020-12-27 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20201223_1418'),
        ('fulfillment', '0286_auto_20201221_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('extra', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'padmin_airway',
            },
        ),
        migrations.CreateModel(
            name='Cashbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.currency')),
            ],
            options={
                'db_table': 'padmin_cashbox',
            },
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'padmin_expense_type',
            },
        ),
        migrations.CreateModel(
            name='PHPTransportation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.JSONField(blank=True, null=True)),
                ('airway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transportations', related_query_name='transportation', to='fulfillment.airway')),
            ],
            options={
                'db_table': 'padmin_transportation',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('cashbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', related_query_name='expense', to='fulfillment.cashbox')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.currency')),
                ('expense_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fulfillment.expensetype')),
            ],
            options={
                'db_table': 'padmin_expense',
            },
        ),
    ]
