# Generated by Django 3.1.2 on 2020-12-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0268_auto_20201126_2301'),
        ('fulfillment', '0286_auto_20201221_1115'),
    ]

    operations = [
    ]
