# Generated by Django 3.1.2 on 2021-01-03 15:52

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0287_merge_20201228_2000'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='courierorder',
            managers=[
                ('archive_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='ticket',
            managers=[
                ('archive_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='customs_goods_list_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='customs_payment_status_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='customs_payment_status_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='declared_to_customs_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_added_to_box',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_declared_by_user',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_declared_to_customs',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_deleted_from_smart_customs',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='is_depeshed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='reg_number',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='CustomsProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=999)),
                ('original_id', models.IntegerField(db_index=True, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', related_query_name='child', to='fulfillment.customsproducttype')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='productcategory',
            name='customs_product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fulfillment.customsproducttype'),
        ),
    ]
