# Generated by Django 3.1.2 on 2020-12-27 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0287_airway_cashbox_expense_expensetype_phptransportation'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='airway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transportations', related_query_name='transportation', to='fulfillment.airway'),
        ),
        migrations.DeleteModel(
            name='PHPTransportation',
        ),
    ]
