# Generated by Django 3.1.2 on 2021-01-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0288_auto_20210103_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='customsproducttype',
            name='name_az',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='customsproducttype',
            name='name_en',
            field=models.CharField(max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='customsproducttype',
            name='name_ru',
            field=models.CharField(max_length=999, null=True),
        ),
    ]
