# Generated by Django 3.1.2 on 2021-01-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0289_auto_20210103_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='airwaybill',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
    ]
