# Generated by Django 3.1.2 on 2021-01-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0290_transportation_airwaybill'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_deleted_from_smart_customs_by_us',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
