# Generated by Django 3.1.2 on 2021-01-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0294_auto_20210109_0230'),
        ('fulfillment', '0288_auto_20201228_0108'),
    ]

    operations = [
    ]
