# Generated by Django 3.1.2 on 2021-01-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0297_remove_multiexpense_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='multi_expense_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
