# Generated by Django 3.1.2 on 2021-02-11 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0299_auto_20210125_2316'),
        ('fulfillment', '0296_auto_20210117_1902'),
    ]

    operations = [
    ]
