# Generated by Django 3.1.2 on 2021-02-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0300_merge_20210211_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='box_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
