# Generated by Django 3.1.2 on 2021-02-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0300_merge_20210211_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='hs_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
