# Generated by Django 3.1.2 on 2021-02-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0301_box_box_number'),
        ('fulfillment', '0301_productcategory_hs_code'),
    ]

    operations = [
    ]
