# Generated by Django 3.1.6 on 2021-03-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0302_merge_20210216_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
