# Generated by Django 3.1.6 on 2021-05-05 15:30

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0303_tariff_deleted_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='tariff',
            managers=[
                ('soft_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_service',
            field=models.CharField(blank=True, choices=[('cybersource', 'Cybersource'), ('paypal', 'PayPal'), ('paytr', 'PayTR')], max_length=30, null=True),
        ),
    ]
