# Generated by Django 3.1.6 on 2021-06-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0304_auto_20210505_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_url',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
    ]
