# Generated by Django 3.1.6 on 2021-07-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0305_auto_20210615_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('card', 'Kart'), ('cash', 'Nağd'), ('balance', 'Balans'), ('terminal', 'Terminal')], default='cash', max_length=10),
        ),
    ]
