# Generated by Django 3.0 on 2020-06-06 10:16

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_az', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to=content.models.get_announcement_image)),
                ('body', models.TextField(blank=True, null=True)),
                ('body_az', models.TextField(blank=True, null=True)),
                ('body_ru', models.TextField(blank=True, null=True)),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'announcement',
            },
        ),
    ]
