# Generated by Django 3.0 on 2020-06-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('question_az', models.CharField(max_length=150, null=True)),
                ('question_ru', models.CharField(max_length=150, null=True)),
                ('answer', models.TextField()),
                ('answer_az', models.TextField(null=True)),
                ('answer_ru', models.TextField(null=True)),
            ],
            options={
                'db_table': 'faq',
            },
        ),
    ]
