# Generated by Django 3.0 on 2020-06-09 15:25

from django.db import migrations
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    try:
        Announcement = apps.get_model("content", "Announcement")
    except LookupError:
        return

    for announcement in Announcement.objects.all():
        if announcement.title:
            announcement.slug = slugify(announcement.title, allow_unicode=True)
        if announcement.title_az:
            announcement.slug_az = slugify(announcement.title_az, allow_unicode=True)
        if announcement.title_ru:
            announcement.slug_ru = slugify(announcement.title_ru, allow_unicode=True)
        announcement.save(update_fields=["slug_az", "slug_ru", "slug"])


def remove_slugs(apps, schema_editor):
    try:
        Announcement = apps.get_model("content", "Announcement")
    except LookupError:
        return

    Announcement.objects.all().update(slug_az=None, slug_ru=None, slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_auto_20200609_1925"),
    ]

    operations = [migrations.RunPython(populate_slugs, reverse_code=remove_slugs)]
