# Generated by Django 3.0 on 2020-06-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_remove_null_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='slug_az',
            field=models.SlugField(allow_unicode=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='slug_ru',
            field=models.SlugField(allow_unicode=True, max_length=100, null=True, unique=True),
        ),
    ]
