# Generated by Django 3.0 on 2020-06-09 19:10

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0007_auto_20200609_2257"),
    ]

    operations = [UnaccentExtension()]
