# Generated by Django 3.0 on 2020-06-13 14:30

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_unaccent_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('title_az', models.CharField(max_length=100, null=True, unique=True)),
                ('title_ru', models.CharField(max_length=100, null=True, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('slug_az', models.SlugField(null=True, unique=True)),
                ('slug_ru', models.SlugField(null=True, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=content.models.get_service_image)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'our_service',
            },
        ),
    ]
