# Generated by Django 3.0 on 2020-06-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(null=True),
        ),
    ]
