# Generated by Django 3.0 on 2020-06-29 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20200629_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='preview_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='preview_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='preview_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='preview_ru',
            field=models.TextField(null=True),
        ),
    ]
