# Generated by Django 3.0 on 2020-07-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_slideritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideritem',
            name='description_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='title_az',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
