# Generated by Django 3.0 on 2020-08-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20200725_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
