# Generated by Django 3.0 on 2020-08-06 20:46

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20200804_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('title_az', models.CharField(max_length=500, null=True, unique=True)),
                ('title_ru', models.CharField(max_length=500, null=True, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('slug_az', models.SlugField(null=True, unique=True)),
                ('slug_ru', models.SlugField(null=True, unique=True)),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('body_az', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('body_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'db_table': 'flat_page',
            },
        ),
    ]
