# Generated by Django 3.0 on 2020-08-24 09:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_auto_20200816_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='body_en_US',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='preview_en_US',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='slug_en_US',
            field=models.SlugField(allow_unicode=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='title_en_US',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en_US',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en_US',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='name_en_US',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='faqcategory',
            name='slug_en_US',
            field=models.SlugField(allow_unicode=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='body_en_US',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='slug_en_US',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='title_en_US',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='footercolumn',
            name='title_en_US',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='footerelement',
            name='title_en_US',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en_US',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='preview_en_US',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='slug_en_US',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en_US',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sitepreset',
            name='about_text_en_US',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitepreset',
            name='main_office_address_en_US',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='description_en_US',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='slideritem',
            name='title_en_US',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
