# Generated by Django 3.0 on 2020-08-25 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_auto_20200824_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='body_en_US',
            new_name='body_en',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='preview_en_US',
            new_name='preview_en',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='slug_en_US',
            new_name='slug_en',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='title_en_US',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='answer_en_US',
            new_name='answer_en',
        ),
        migrations.RenameField(
            model_name='faq',
            old_name='question_en_US',
            new_name='question_en',
        ),
        migrations.RenameField(
            model_name='faqcategory',
            old_name='name_en_US',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='faqcategory',
            old_name='slug_en_US',
            new_name='slug_en',
        ),
        migrations.RenameField(
            model_name='flatpage',
            old_name='body_en_US',
            new_name='body_en',
        ),
        migrations.RenameField(
            model_name='flatpage',
            old_name='slug_en_US',
            new_name='slug_en',
        ),
        migrations.RenameField(
            model_name='flatpage',
            old_name='title_en_US',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='footercolumn',
            old_name='title_en_US',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='footerelement',
            old_name='title_en_US',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='description_en_US',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='preview_en_US',
            new_name='preview_en',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='slug_en_US',
            new_name='slug_en',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='title_en_US',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='sitepreset',
            old_name='about_text_en_US',
            new_name='about_text_en',
        ),
        migrations.RenameField(
            model_name='sitepreset',
            old_name='main_office_address_en_US',
            new_name='main_office_address_en',
        ),
        migrations.RenameField(
            model_name='slideritem',
            old_name='description_en_US',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='slideritem',
            old_name='title_en_US',
            new_name='title_en',
        ),
    ]
