# Generated by Django 3.0 on 2020-09-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_auto_20200825_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='type',
            field=models.CharField(choices=[('ct', 'Terms and conditions'), ('st', 'Simple flat page'), ('ot', 'Offer text')], default='st', max_length=2),
        ),
    ]
