# Generated by Django 3.0 on 2020-09-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_flatpage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreset',
            name='about_text_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitepreset',
            name='about_text_title_az',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitepreset',
            name='about_text_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sitepreset',
            name='about_text_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
