# Generated by Django 3.0 on 2020-09-07 17:08

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0029_auto_20200907_1139"),
    ]

    operations = [TrigramExtension()]
