# Generated by Django 3.1.1 on 2020-09-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_trigram_similar_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpage',
            name='preview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='preview_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='preview_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flatpage',
            name='preview_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
