# Generated by Django 3.1.1 on 2020-09-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_auto_20200910_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepreset',
            name='about_text_preview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitepreset',
            name='about_text_preview_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitepreset',
            name='about_text_preview_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitepreset',
            name='about_text_preview_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
