# Generated by Django 3.1.2 on 2021-02-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_auto_20200910_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='slug_az',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='slug_en',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='slug_ru',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
