# Generated by Django 3.0 on 2020-05-30 15:29

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20200529_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Kişi'), ('F', 'Qadın')], max_length=1, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('id_serial', models.CharField(choices=[('AZE', 'AZE'), ('AA', 'AA')], max_length=3, null=True)),
                ('id_number', models.CharField(blank=True, max_length=8, null=True)),
                ('id_pin', models.CharField(blank=True, max_length=7, null=True)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
    ]
