# Generated by Django 3.0 on 2020-05-30 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0001_initial'),
        ('customer', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fulfillment.Warehouse'),
        ),
    ]
