# Generated by Django 3.0 on 2020-06-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='house_numbers',
            new_name='house_number',
        ),
    ]
