# Generated by Django 3.0 on 2020-06-21 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_address_nearby_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='warehouse',
        ),
    ]
