# Generated by Django 3.0 on 2020-07-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_address_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_created_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
