# Generated by Django 3.0 on 2020-07-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_user_is_created_by_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='type',
            field=models.CharField(choices=[('user', 'İstifadəçi'), ('admin', 'Admin'), ('cashier', 'Kassir'), ('warehouseman', 'Anbardar'), ('shopping_assistant', 'Alış-veriş köməkçisi'), ('content_manager', 'Kontent menecer'), ('monitor', 'Monitor')], max_length=20, unique=True),
        ),
    ]
