# Generated by Django 3.0 on 2020-07-24 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_auto_20200722_1712'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
