# Generated by Django 3.0 on 2020-07-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_auto_20200725_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='type',
            field=models.CharField(choices=[('user', 'İstifadəçi'), ('admin', 'Admin'), ('cashier', 'Kassir'), ('warehouseman', 'Anbardar'), ('shopping_assistant', 'Alış-veriş köməkçisi'), ('content_manager', 'Kontent menecer'), ('customer_service', 'Müştəri xidməti'), ('monitor', 'Monitor'), ('courier', 'Kuryer')], max_length=20, unique=True),
        ),
    ]
