# Generated by Django 3.0 on 2020-08-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_user_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='type',
            field=models.CharField(choices=[('user', 'İstifadəçi'), ('admin', 'Admin'), ('cashier', 'Kassir'), ('warehouseman', 'Anbardar'), ('shopping_assistant', 'Alış-veriş köməkçisi'), ('content_manager', 'Kontent menecer'), ('customer_service', 'Müştəri xidməti'), ('monitor', 'Monitor'), ('courier', 'Kuryer'), ('customs_agent', 'Gömrük Agenti')], max_length=20, unique=True),
        ),
    ]
