# Generated by Django 3.0 on 2020-08-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_auto_20200829_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='address_extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
