# Generated by Django 3.0 on 2020-08-29 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_recipient_address_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrozenRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=510)),
                ('phone_number', models.CharField(max_length=20)),
                ('id_pin', models.CharField(db_index=True, max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frozen_recipients', related_query_name='frozen_recipient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'frozen_customer_recipient',
            },
        ),
    ]
