# Generated by Django 3.0 on 2020-08-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0033_frozenrecipient_real_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='frozenrecipient',
            name='gender',
            field=models.CharField(choices=[('M', 'Kişi'), ('F', 'Qadın')], default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipient',
            name='gender',
            field=models.CharField(choices=[('M', 'Kişi'), ('F', 'Qadın')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
