# Generated by Django 3.0 on 2020-08-30 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0034_auto_20200830_1340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
