# Generated by Django 3.0 on 2020-09-01 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0199_auto_20200901_1051'),
        ('customer', '0035_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fulfillment.CourierRegion'),
        ),
    ]
