# Generated by Django 3.0 on 2020-09-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0036_recipient_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
