# Generated by Django 3.1.1 on 2020-09-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0037_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='extra',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
