# Generated by Django 3.1.1 on 2020-09-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0038_auto_20200908_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='frozenrecipient',
            name='address',
            field=models.TextField(default='Fake address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frozenrecipient',
            name='address_extra',
            field=models.TextField(blank=True, null=True),
        ),
    ]
