# Generated by Django 3.1.1 on 2020-10-01 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0040_auto_20201001_2341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='photo_blob',
            new_name='photo_base64',
        ),
    ]
