# Generated by Django 3.1.2 on 2020-11-07 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0264_promocode_promocodebenefit'),
        ('customer', '0041_auto_20201002_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registered_promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_users', related_query_name='registered_user', to='fulfillment.promocode'),
        ),
    ]
