# Generated by Django 3.1.2 on 2020-12-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0044_auto_20201205_1921'),
        ('customer', '0042_user_registered_promo_code'),
    ]

    operations = [
    ]
