# Generated by Django 3.1.2 on 2021-01-13 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fulfillment', '0295_merge_20210110_1500'),
        ('customer', '0045_merge_20201209_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prefered_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fulfillment.warehouse'),
        ),
    ]
