# Generated by Django 3.1.2 on 2021-01-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0046_user_prefered_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frozenrecipient',
            name='id_pin',
            field=models.CharField(db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='id_pin',
            field=models.CharField(db_index=True, max_length=8),
        ),
    ]
