# Generated by Django 3.1.2 on 2021-02-13 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0047_auto_20210130_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frozenrecipient',
            name='id_pin',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='id_pin',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
