# Generated by Django 3.0 on 2020-05-28 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('name_az', models.CharField(max_length=20, null=True)),
                ('name_ru', models.CharField(max_length=20, null=True)),
                ('symbol', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=4, default=1, max_digits=9)),
            ],
            options={
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('name_az', models.CharField(max_length=50, null=True, unique=True)),
                ('name_ru', models.CharField(max_length=50, null=True, unique=True)),
                ('is_base', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('phone_code', models.CharField(max_length=10, unique=True)),
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Currency')),
            ],
            options={
                'db_table': 'country',
            },
        ),
    ]
