# Generated by Django 3.0 on 2020-05-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default='AZE', max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
