# Generated by Django 3.0 on 2020-05-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='code',
            field=models.CharField(default='AZN', max_length=5, unique=True),
            preserve_default=False,
        ),
    ]
