# Generated by Django 3.0 on 2020-05-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_az',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_ru',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
