# Generated by Django 3.0 on 2020-06-02 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200530_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('prefix', models.CharField(max_length=5)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_operators', related_query_name='mobile_operator', to='core.Country')),
            ],
            options={
                'db_table': 'mobile_operator',
            },
        ),
    ]
