# Generated by Django 3.0 on 2020-06-09 18:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_country_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.get_map_image),
        ),
    ]
