# Generated by Django 3.0 on 2020-07-24 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_city_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Currencies'},
        ),
    ]
