# Generated by Django 3.0 on 2020-07-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
