# Generated by Django 3.0 on 2020-08-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_currencyratelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='order_commission_info_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='order_commission_info_text_az',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='order_commission_info_text_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
