# Generated by Django 3.0 on 2020-08-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200807_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_default_destination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='country',
            name='is_default_destination',
            field=models.BooleanField(default=False),
        ),
    ]
