# Generated by Django 3.0 on 2020-08-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200819_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='cybersource_redirect_url',
            field=models.URLField(blank=True, help_text='URL to redirect to after payment completion', null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='paypal_redirect_url',
            field=models.URLField(blank=True, help_text='URL to redirect to after payment approval', null=True),
        ),
    ]
