# Generated by Django 3.0 on 2020-08-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200821_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='email_verification_url',
            field=models.URLField(blank=True, help_text='Front app URL for verifying email address', null=True),
        ),
    ]
