# Generated by Django 3.0 on 2020-08-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_configuration_email_verification_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_en_US',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='order_commission_info_text_en_US',
            field=models.TextField(blank=True, help_text='Text that will be shown to user on order create page', null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='description_en_US',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='name_en_US',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='name_en_US',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
