# Generated by Django 3.0 on 2020-08-25 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200824_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name_en_US',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='order_commission_info_text_en_US',
            new_name='order_commission_info_text_en',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='description_en_US',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='name_en_US',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='currency',
            old_name='name_en_US',
            new_name='name_en',
        ),
    ]
