# Generated by Django 3.0 on 2020-09-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_country_flag_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
