# Generated by Django 3.1.1 on 2020-09-08 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_configuration_notifications_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='monthly_spendings_danger_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='monthly_spendings_danger_message_az',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='monthly_spendings_danger_message_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='monthly_spendings_danger_message_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='monthly_spendings_danger_treshold',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=9),
        ),
        migrations.AddField(
            model_name='configuration',
            name='monthly_spendings_treshold_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.currency'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='monthly_spendings_warning_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='monthly_spendings_warning_message_az',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='monthly_spendings_warning_message_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='monthly_spendings_warning_message_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='monthly_spendings_warning_treshold',
            field=models.DecimalField(decimal_places=2, default=250, max_digits=9),
        ),
    ]
