# Generated by Django 3.1.1 on 2020-09-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20200908_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='number',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
