# Generated by Django 3.1.1 on 2020-09-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_currency_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='number',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
