# Generated by Django 3.1.1 on 2020-09-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_country_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='number',
            field=models.CharField(blank=True, help_text='<a href="https://www.iban.com/country-codes">Full list of currency codes and numbers</a>', max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='number',
            field=models.CharField(blank=True, help_text='<a href="https://www.iban.com/currency-codes">Full list of currency codes and numbers</a>', max_length=5, null=True, unique=True),
        ),
    ]
