# Generated by Django 3.1.1 on 2020-09-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20200909_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(help_text='<b>Alpha-2 code of country. See the link below</b>', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='number',
            field=models.CharField(blank=True, help_text='<a target="blank" href="https://www.iban.com/country-codes">Full list of country codes and numbers</a>', max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='number',
            field=models.CharField(blank=True, help_text='<a target="blank" href="https://www.iban.com/currency-codes">Full list of currency codes and numbers</a>', max_length=5, null=True, unique=True),
        ),
    ]
