# Generated by Django 3.1.1 on 2020-09-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_configuration_manifest_reports_sent_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name_az',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
