# Generated by Django 3.1.1 on 2020-09-19 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20200915_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineShoppingDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Example: trendyol', max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_domains', related_query_name='shopping_domain', to='core.country')),
            ],
            options={
                'db_table': 'online_shopping_domain',
            },
        ),
    ]
