# Generated by Django 3.1.2 on 2020-11-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20200922_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='invited_friend_benefits_count',
            field=models.PositiveIntegerField(default=2, help_text='How many transactions must an invited friend complete? How many transactions will be discounteed for invited friend and user who invited that friend?'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='invited_friend_discount_pecentage',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=9),
        ),
    ]
