# Generated by Django 3.1.2 on 2020-11-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0042_auto_20201108_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='invite_friend_discount_appliable_models',
            field=models.ManyToManyField(limit_choices_to={'model__in': ['shipment', 'order', 'courierorder']}, to='contenttypes.ContentType'),
        ),
    ]
