# Generated by Django 3.1.2 on 2020-11-20 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_configuration_invite_friend_discount_appliable_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='invited_friend_discount_pecentage',
            new_name='invited_friend_cashback_percentage',
        ),
    ]
