# Generated by Django 3.1.2 on 2020-12-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20201120_1615'),
        ('core', '0042_auto_20201202_2232'),
    ]

    operations = [
    ]
