# Generated by Django 3.1.2 on 2020-12-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0045_merge_20201209_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='invite_friend_discount_appliable_models',
            field=models.ManyToManyField(blank=True, limit_choices_to={'model__in': ['shipment', 'order', 'courierorder']}, to='contenttypes.ContentType'),
        ),
    ]
