# Generated by Django 3.1.2 on 2021-01-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20201223_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_smart_customs_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
