# Generated by Django 3.1.2 on 2021-01-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_country_is_smart_customs_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='smart_customs_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
