# Generated by Django 3.1.2 on 2021-01-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_configuration_smart_customs_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='smart_customs_fail_silently',
            field=models.BooleanField(default=False),
        ),
    ]
