# Generated by Django 3.1.6 on 2021-05-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_configuration_smart_customs_fail_silently'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='paytr_redirect_url',
            field=models.URLField(blank=True, help_text='URL to redirect to after payment completion', null=True),
        ),
    ]
